[workspace]
members = [
  "libraries/common",
  "libraries/utils",
  "proc_macros/generate_config",
  "proc_macros/safe_arithmetic",
]
resolver = "2"

[workspace.package]
description = "A collection of utility packages for the Weft Foundation blueprints"
edition = "2021"

[workspace.dependencies]
# Scrypto
scrypto = {version = "1.3.0"}
scrypto-test = {version = "1.3.0"}

# Others
anyhow = "1.0"
paste = "1.0"

# Local dependencies
common= {path = "libraries/common"}
utils = {path = "libraries/utils"}
generate_config = {path = "proc_macros/generate_config"}
safe_arithmetic =  {path = "proc_macros/safe_arithmetic"}


[profile.release]
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
lto = true # Enable Link Time Optimization.
opt-level = 'z' # Optimize for size.
overflow-checks = true # Panic in the case of an overflow.
panic = 'abort' # Abort on panic.
strip = true # Strip the symbols.

[workspace.lints.clippy]
arithmetic_side_effects = "warn"
type_complexity = "allow"
too_many_arguments = "allow"
# complexity = "allow"

